### PR TITLE
Adjust database seeds to naming strategy change in resource-server

### PR DESCRIPTION
**Pull request by dacrome**
Needs merged https://github.com/osiam/resource-server/pull/28

### CODE REVIEW

**Comment by dacrome** [comment]
rebased. who wants to merge? But please merge above mentioned resource-server PR before.

**Comment by tkrille** [comment]
ITs are failing. You forgot one `meta_id` in `src/test/resources/database_seeds/RefreshTokenGrantIT/database_seed.xml`.

**Comment by dacrome** [comment]
ups. changed.

**Comment by dacrome** [comment]
Like already commented in the referenced resource-server PR, with mysql the test are failing with the renamed `is_primary` columns to `primary`:

```
provide_an_invalid_access_token_raises_exception(org.osiam.client.EditUserServiceIT)  Time elapsed: 0.293 sec  <<< ERROR!
org.dbunit.DatabaseUnitException: Exception processing table name='scim_email'
...
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'primary, type, user_internal_id) values (100091, 'adavies@example.com', 0, 'work' at line 1
```

I have currently no time to investigate why this happens...

**Comment by wallner** [comment]
`primary` is a [reserved word](https://dev.mysql.com/doc/refman/5.6/en/keywords.html) in MySQL. That is a shame and probably means that we have to keep it as is_required.

**Comment by dacrome** [comment]
Yes, but reserved words are useable when escaping with backticks like [here](https://dev.mysql.com/doc/refman/5.6/en/identifiers.html) described. Maybe in the dbunit generated sql the column names aren't escaped?

**Comment by tkrille** [comment]
Cool, [problem solved](https://github.com/osiam/connector4java-integration-tests/pull/259). Just in time. I'm now starting to test this

**Comment by tkrille** [comment]
ITs are still failing. Here's an error message from the servers:

```
2015-07-16 19:38:05 org.hibernate.engine.jdbc.spi.SqlExceptionHelper [ERROR] FEHLER: Syntaxfehler bei „primary“
  Position: 25
```

Seems that hibernate doesn't escape special names neither.

**Comment by tkrille** [comment]
Looks like that escaping in Hibernate only works in `SELECT` statements. At least only the tests that write data (and writing a multi-valued attribute) are failing. I'd recommend we revert the rename of the `is_primary` column. Seems to be simply too much trouble just for the sake of removing 1 useless annotation.

**Comment by wallner** [comment]
@tkrille: I agree.

**Comment by dacrome** [comment]
I also agree and renamed `primary` back to `is_primary`

**Comment by dacrome** [comment]
what about this one?

**Comment by wallner** [comment]
@dacrome You did it! Thank you for your effort! We are through with it.

**Pull request merged**
