### PR TITLE
Clean up testing for exceptions

### PR DESCRIPTION
**Pull request by wallner**
This pull request adjusts the integration tests to work with the changes made in osiam/resource-server#65 while working on the exception handling I also made use of Junits `@Rule` notation to handle the expected exceptions.

### CODE REVIEW

**Comment by tkrille** [comment]
@dacrome I've assigned you, because you're also assigned to osiam/resource-server#65.

**Comment by dacrome** [comment]
What about the 9 remain `fail()` calls? I know they don't used to be as expected fail, but maybe some can be deleted?

**Comment by dacrome** [comment]
> What about the 9 remain fail() calls? I know they don't used to be as expected fail, but maybe some can be deleted?

Ok, this is out of scope for this PR. Anyway, most of the tests that using `fail()` need a cleanup!

**Comment by dacrome** [comment]
Thanks!

**Pull request merged**
