### PR TITLE
Adjust database seeds to naming strategy change in auth-server

### PR DESCRIPTION
**Pull request by dacrome**

### CODE REVIEW

**Comment by dacrome** [comment]
rebased. who wants to merge? But please merge above referenced auth-server PR before.

**Comment by tkrille** [comment]
ITs are failing:

```
Tests in error: 
  RefreshTokenGrantIT.refreshing_an_access_token_should_provide_a_new_access_token » NoSuchColumn
  RefreshTokenGrantIT.refreshing_an_access_token_when_expired » NoSuchColumn osi...
```

Details:
```
refreshing_an_access_token_should_provide_a_new_access_token(org.osiam.client.RefreshTokenGrantIT)  Time elapsed: 0.047 sec  <<< ERROR!
org.dbunit.dataset.NoSuchColumnException: osiam_client.ACCESSTOKENVALIDITYSECONDS -  (Non-uppercase input column: accesstokenvalidityseconds) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.
```

and

```
refreshing_an_access_token_when_expired(org.osiam.client.RefreshTokenGrantIT)  Time elapsed: 0.078 sec  <<< ERROR!
org.dbunit.dataset.NoSuchColumnException: osiam_client.ACCESSTOKENVALIDITYSECONDS -  (Non-uppercase input column: accesstokenvalidityseconds) in ColumnNameToIndexes cache map. Note that the map's column names are NOT case sensitive.
```

I think you missed the file `src/test/resources/database_seeds/RefreshTokenGrantIT/database_seed.xml`. I introduced some weeks ago after your changes.

**Comment by dacrome** [comment]
updated

**Comment by tkrille** [comment]
whoa, that was fast :) I'm re-running the tests ...

**Comment by tkrille** [comment]
Don't forget the resource-server's PR.

**Pull request merged**
