### PR TITLE
Move Docker stuff to test sources

### PR DESCRIPTION
**Pull request by tkrille**
This has been bothering me for a long time. I really think it should belong to the test sources. We have no main artifact and therefore no main sources in this project.

### CODE REVIEW

**Comment by dacrome** [comment]
Yes, me too! Thanks for changing the source folder to test sources. Actually the tests are failing because you forgot to move the [classes folder of the greenmail folder](https://github.com/osiam/connector4java-integration-tests/tree/master/src/main/docker/tomcat/greenmail-webapp-1.4.1/WEB-INF/classes/com/icegreen/greenmail/webapp) that's why an `java.lang.ClassNotFoundException: com.icegreen.greenmail.webapp.GreenMailListener` occurred and all self-administration tests failing.

**Comment by tkrille** [comment]
But it works on my machine. Why that?

**Comment by tkrille** [comment]
Haha. These are `*.class` files. They will be ignored by Git :)

**Comment by tkrille** [comment]
At least by my Git ;)

**Comment by tkrille** [comment]
Alright, this should be good to go now.

**Comment by tkrille** [comment]
Cool, it works. Thanks a lot @dacrome! You want to merge this now?

**Comment by dacrome** [comment]
Thanks!

**Pull request merged**
