### PR TITLE
Add tests for ME scope (auth-server)

### PR DESCRIPTION
**Pull request by tkrille**
PR for auth-server is coming soon.

### CODE REVIEW

**Comment by dacrome** [comment]
Why didn't GitHub recognize the already merged commit?

**Comment by tkrille** [comment]
dunno, but rebased.

**Comment by dacrome** [comment]
If https://github.com/osiam/auth-server/pull/16 and https://github.com/osiam/connector4java/pull/131 are merged, I will merge this. Nice work!

**Comment by tkrille** [comment]
I'm still wondering whether we need more tests. But this is a topic for another PR.

**Pull request merged**
